FROM oven/bun:latest AS build

WORKDIR /app

COPY frontend/ .

RUN bun install && bun run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]