/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateUsersImport } from './routes/create-users'
import { Route as AllUsersImport } from './routes/all-users'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const CreateUsersRoute = CreateUsersImport.update({
  id: '/create-users',
  path: '/create-users',
  getParentRoute: () => rootRoute,
} as any)

const AllUsersRoute = AllUsersImport.update({
  id: '/all-users',
  path: '/all-users',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/all-users': {
      id: '/all-users'
      path: '/all-users'
      fullPath: '/all-users'
      preLoaderRoute: typeof AllUsersImport
      parentRoute: typeof rootRoute
    }
    '/create-users': {
      id: '/create-users'
      path: '/create-users'
      fullPath: '/create-users'
      preLoaderRoute: typeof CreateUsersImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/all-users': typeof AllUsersRoute
  '/create-users': typeof CreateUsersRoute
  '/about': typeof AboutLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/all-users': typeof AllUsersRoute
  '/create-users': typeof CreateUsersRoute
  '/about': typeof AboutLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/all-users': typeof AllUsersRoute
  '/create-users': typeof CreateUsersRoute
  '/about': typeof AboutLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/all-users' | '/create-users' | '/about'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/all-users' | '/create-users' | '/about'
  id: '__root__' | '/' | '/all-users' | '/create-users' | '/about'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AllUsersRoute: typeof AllUsersRoute
  CreateUsersRoute: typeof CreateUsersRoute
  AboutLazyRoute: typeof AboutLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AllUsersRoute: AllUsersRoute,
  CreateUsersRoute: CreateUsersRoute,
  AboutLazyRoute: AboutLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/all-users",
        "/create-users",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/all-users": {
      "filePath": "all-users.tsx"
    },
    "/create-users": {
      "filePath": "create-users.tsx"
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
